version: '3'

services:
  postgres:
    image: 'postgres:10.3'

  web:
    build: .
    command: bash -c "build-scripts/web/initialize.sh"
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/tasknight
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres

  web_production:
    build: .
    command: bash -c "build-scripts/web/initialize_production.sh"
    restart: on-failure
    volumes:
      - .:/var/www/tasknight
    ports:
      - "80:80"
    depends_on:
      - postgres
    links:
      - postgres
