# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/character_attributes', type: :request do
  # CharacterAttribute. As you add validations to CharacterAttribute, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      CharacterAttribute.create! valid_attributes
      get character_attributes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      character_attribute = CharacterAttribute.create! valid_attributes
      get character_attribute_url(character_attribute)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_character_attribute_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      character_attribute = CharacterAttribute.create! valid_attributes
      get edit_character_attribute_url(character_attribute)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new CharacterAttribute' do
        expect do
          post character_attributes_url, params: { character_attribute: valid_attributes }
        end.to change(CharacterAttribute, :count).by(1)
      end

      it 'redirects to the created character_attribute' do
        post character_attributes_url, params: { character_attribute: valid_attributes }
        expect(response).to redirect_to(character_attribute_url(CharacterAttribute.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new CharacterAttribute' do
        expect do
          post character_attributes_url, params: { character_attribute: invalid_attributes }
        end.to change(CharacterAttribute, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post character_attributes_url, params: { character_attribute: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested character_attribute' do
        character_attribute = CharacterAttribute.create! valid_attributes
        patch character_attribute_url(character_attribute), params: { character_attribute: new_attributes }
        character_attribute.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the character_attribute' do
        character_attribute = CharacterAttribute.create! valid_attributes
        patch character_attribute_url(character_attribute), params: { character_attribute: new_attributes }
        character_attribute.reload
        expect(response).to redirect_to(character_attribute_url(character_attribute))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        character_attribute = CharacterAttribute.create! valid_attributes
        patch character_attribute_url(character_attribute), params: { character_attribute: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested character_attribute' do
      character_attribute = CharacterAttribute.create! valid_attributes
      expect do
        delete character_attribute_url(character_attribute)
      end.to change(CharacterAttribute, :count).by(-1)
    end

    it 'redirects to the character_attributes list' do
      character_attribute = CharacterAttribute.create! valid_attributes
      delete character_attribute_url(character_attribute)
      expect(response).to redirect_to(character_attributes_url)
    end
  end
end
