# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/character_classes', type: :request do
  # CharacterClass. As you add validations to CharacterClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      CharacterClass.create! valid_attributes
      get character_classes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      character_class = CharacterClass.create! valid_attributes
      get character_class_url(character_class)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_character_class_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      character_class = CharacterClass.create! valid_attributes
      get edit_character_class_url(character_class)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new CharacterClass' do
        expect do
          post character_classes_url, params: { character_class: valid_attributes }
        end.to change(CharacterClass, :count).by(1)
      end

      it 'redirects to the created character_class' do
        post character_classes_url, params: { character_class: valid_attributes }
        expect(response).to redirect_to(character_class_url(CharacterClass.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new CharacterClass' do
        expect do
          post character_classes_url, params: { character_class: invalid_attributes }
        end.to change(CharacterClass, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post character_classes_url, params: { character_class: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested character_class' do
        character_class = CharacterClass.create! valid_attributes
        patch character_class_url(character_class), params: { character_class: new_attributes }
        character_class.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the character_class' do
        character_class = CharacterClass.create! valid_attributes
        patch character_class_url(character_class), params: { character_class: new_attributes }
        character_class.reload
        expect(response).to redirect_to(character_class_url(character_class))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        character_class = CharacterClass.create! valid_attributes
        patch character_class_url(character_class), params: { character_class: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested character_class' do
      character_class = CharacterClass.create! valid_attributes
      expect do
        delete character_class_url(character_class)
      end.to change(CharacterClass, :count).by(-1)
    end

    it 'redirects to the character_classes list' do
      character_class = CharacterClass.create! valid_attributes
      delete character_class_url(character_class)
      expect(response).to redirect_to(character_classes_url)
    end
  end
end
